name: Babihost Login Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  babihostlogin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Create Report Directory
        run: mkdir -p reports/assets

      - name: Run Babihost Login
        run: |
          venv/bin/python -m pytest \
            --html=reports/BabihostLogin.html \
            -k "TestBabihostLogin" \
            --css=reports/assets/style.css
        env:
          DISPLAY: :99

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BabihostLogin-Report
          path: reports
